### PR TITLE
feat: add initial CI

### LINKED ISSUE #4: add initial CI checks
At a minimum we should have CI checks for conventional commit messages as well as running the unit tests.

### PR DESCRIPTION
**Pull request by westonpace**
Closes #4 

BREAKING CHANGE: The cmake option `BUILD_TESTING` is now named `SUBSTRAIT_CPP_BUILD_TESTING`

### CODE REVIEW

**Comment by westonpace** [comment]
BREAKING DEV CHANGE: This changes the setup-ubuntu.sh script to install protobuf from apt instead of building it from source (the way it was doing so was not compatible with github-actions and this is faster anyways).

BREAKING DEV CHANGE: The build now specifies where tests and libraries are placed.  So, instead of the default, libraries will go into `build_dir/<config>/lib` (e.g. `build_dir/debug/lib`) and tests will go into `build_dir/<config>/tests`.

Testing was not previously enabled so you should now be able to run tests with `ctest` in addition to running them individually.

**Comment by westonpace** [comment]
CC @chaojun-zhang please take a look

**Review by EpsilonPrime — APPROVED** [review]
LGTM

**Comment by vibhatha** [comment]
@westonpace Looks good to me. 

Should we update the `Dockerfile` too? There are some changes to the build.

**Comment by chaojun-zhang** [comment]
LGTM

**Comment by chaojun-zhang** [comment]
> CC @chaojun-zhang please take a look

LGTM

**Review by chaojun-zhang — APPROVED** [review]

**Review by vibhatha — APPROVED** [review]

**Pull request merged**
