### PR TITLE
fix: correct cmake library interdependencies

### PR DESCRIPTION
**Pull request by EpsilonPrime**
This eliminates the cycles described in #99.

PlanPrinterVisitor is now part of symbol_table.
BasePlanProtoVisitor (which PlanPrinterVisitor depends on) is now its own library.

### CODE REVIEW

**Comment by ingomueller-net** [comment]
Awesome -- thank you for the quick fix! Probably a much better fix than what I had in mind :)

For completeness, here are the dependency graphs before and after this PR. Before the change, we can see several inter-dependent targets; after the change, it's a nice DAG.

**Before:**

before

**After:**

after

I generated them running `cmake --graphviz=foo.dot .. -DBUILD_SHARED_LIBS=OFF && dot -Tpng -o foo.png foo.dot` in the build folder, where I put a file called `CMakeGraphVizOptions.cmake` with the following content

```cmake
set(GRAPHVIZ_IGNORE_TARGETS "absl_*;gmock*;gtest*;protobuf*;yaml-cpp*;fmt*;-lrt;Threads*;/usr/*;.*_test"
```

**Review by westonpace — APPROVED** [review]
Approve if CI passes.  I won't pretend to have fully internalized these changes but I don't see anything odd or out of place.

**Comment by EpsilonPrime** [comment]
Thanks for finding this issue as well as providing the visualization of the dependencies.  I'll probably use this trick to prevent such issues in the future.

**Comment by ingomueller-net** [comment]
> Thanks for finding this issue as well as providing the visualization of the dependencies. I'll probably use this trick to prevent such issues in the future.

Sure thing! Another possibility is to (also) build with `BUILD_SHARED_LIBS` in CI...

**Pull request merged**
