### PR TITLE
fix(naming):  Rename namespace 'substrait' to 'io::substrait'

### PR DESCRIPTION
**Pull request by chaojun-zhang**
Rename namespace from 'substrait' to 'io::substrait' to avoid conflicts with namespace defined in substrait proto files.

### CODE REVIEW

**Comment by chaojun-zhang** [comment]
@westonpace can you help to review and trigger the check? thanks

**Comment by vibhatha** [comment]
@chaojun-zhang sure I will take a look.

**Review by vibhatha — APPROVED** [review]
@chaojun-zhang Thanks for working on this. LGTM!

**Comment by westonpace** [comment]
Closes #8

**Comment by westonpace** [comment]
I'll merge this since it is best to get this kind of change in quickly.  However, I am concerned about the lack of automated tests on this repository.

**Review by westonpace — APPROVED** [review]

**Pull request merged**
